### ISSUE TITLE
Special characters in passwords result in login failed

### ISSUE THREAD

**Issue by ridv** [burntcookie90/librofm-downloader#161]
**Describe the bug**

Had a password with `%` and `$` characters in it and could not log in. Changed my password to not have any special characters and was finally able to log in. Not sure if it was the `%` or the `$` character that was causing issues but I suspect it was `$`.

Before changing the password, I tried escaping it with `\$` but still couldn't get it to work.

**To Reproduce**

Change libro.fm password to include a `$`.
Attempt to log in using library.

**Expected behavior**

Should be able to log in as long as the password is valid for the website itself.

**Logs**
Enable `VERBOSE` to get the real stuff. If applicable, add screenshots to help explain your problem.

** Environment **
libro-fm-downloader:

docker-compose.yml: 

```yaml
services:
  librofm-downloader:
    image: ghcr.io/burntcookie90/librofm-downloader:latest
    volumes:
      - /volume1/docker/librofm-downloader:/data
      - /volume1/media/Audiobooks/librofm:/media
    environment:
      - LIBRO_FM_USERNAME=<redacted>
      - LIBRO_FM_PASSWORD=<redacted>
      - SYNC_INTERVAL=w
    ports:
      # optional if you want to use the /update webhook
      - 9393:8080
```

**Additional context**
