### ISSUE TITLE
 java.lang.IllegalStateException: Unhandled sync interval

### ISSUE THREAD

**Issue by drallgood** [burntcookie90/librofm-downloader#32]
**Describe the bug**
Seems like after a sync with libro.fm and subsequent checking of the local files it crashed

**To Reproduce**
No clue. Just started happening. I'll dig deeper later

**Expected behavior**

**Logs**
librofm-downloader-1  | Sync Interval: null
librofm-downloader-1  | Exception in thread "main" java.lang.IllegalStateException: Unhandled sync interval
librofm-downloader-1  |         at com.vishnurajeevan.libroabs.Run$run$1$1.invokeSuspend(Application.kt:119)
librofm-downloader-1  |         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
librofm-downloader-1  |         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
librofm-downloader-1  |         at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
librofm-downloader-1  |         at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
librofm-downloader-1  |         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
librofm-downloader-1  |         at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
librofm-downloader-1  |         at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
librofm-downloader-1  |         at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
librofm-downloader-1  |         at com.vishnurajeevan.libroabs.Run.run(Application.kt:98)
librofm-downloader-1  |         at com.github.ajalt.clikt.core.CoreCliktCommandKt.parse(CoreCliktCommand.kt:107)
librofm-downloader-1  |         at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:78)
librofm-downloader-1  |         at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:90)
librofm-downloader-1  |         at com.vishnurajeevan.libroabs.ApplicationKt.main(Application.kt:36)
** Environment **
libro-fm-downloader:

docker-compose.yml: 

```yaml
librofm-downloader:
    image: ghcr.io/burntcookie90/librofm-downloader:main
    user: "$PUID:$PGID"
    volumes:
      - ${DATADIR}/libro/librofm-downloader:/data
      - ${HDDDATADIR}/books/Audiobooks/:/media
    env_file:
      - libro.env
```

**Additional context**
