### ISSUE TITLE
Chapter rename fails with characters forbidden by the filesystem

### ISSUE THREAD

**Issue by coffeemonk** [burntcookie90/librofm-downloader#67]
**Describe the bug**

Renaming chapter files fails when a rename operation results in a filename with forbidden characters (like "\")

**To Reproduce**
1. Enable chapter renaming
2. Download a book with a disallowed character in the chapter name, such as "Chapter 29: LOC/LOM: Clarke Station Population: 23: Days to Ryugu Departure" from the book "Critical Mass" by Daniel Suarez

**Expected behavior**
The chapter file is renamed as expected, with appropriate character replacements to prevent filesystem issues.
Alternately: All file names should be encapsulated as necessary (by quotes or whatever method is required by the context) when attempting read or write operations.

**Logs**

Mar 05, 2025 1:29:24 AM org.jaudiotagger.audio.AudioFile checkFileExists

SEVERE: Unable to find:/media/Daniel Suarez/Critical Mass/31 - Critical Mass - Chapter 29: LOC/LOM: Clarke Station Population: 23: Days to Ryugu Departure: 998.mp3

Exception in thread "main" java.io.FileNotFoundException: Unable to find:/media/Daniel Suarez/Critical Mass/31 - Critical Mass - Chapter 29: LOC/LOM: Clarke Station Population: 23: Days to Ryugu Departure: 998.mp3
	at org.jaudiotagger.audio.AudioFile.checkFileExists(AudioFile.java:224)
	at org.jaudiotagger.audio.AudioFile.checkFilePermissions(AudioFile.java:241)
	at org.jaudiotagger.audio.mp3.MP3File.<init>(MP3File.java:382)
	at org.jaudiotagger.audio.mp3.MP3FileReader.read(MP3FileReader.java:39)
	at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:356)
	at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:192)
	at com.vishnurajeevan.libroabs.libro.LibroApiHandler$renameChapters$2.invokeSuspend(LibroFmClient.kt:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)

** Environment **

docker-compose.yml: 

```yaml
services:
  librofm-downloader:
    image: ghcr.io/burntcookie90/librofm-downloader:latest
    # network_mode: host
    volumes:
      - /share/Container/librofm-downloader/data:/data
      - '/share/Documents/3. Resources/Audiobooks/LibroFM Library:/media'
    # ports:
      # optional if you want to use the /update webhook
      # - 8480:8080 
    environment:
      - LIBRO_FM_USERNAME=${LF_USER}
      - LIBRO_FM_PASSWORD=${LF_PASS}
      - SYNC_INTERVAL=h  # h/d/w — choose one
      - RENAME_CHAPTERS=true
      - WRITE_TITLE_TAG=true #this one requires RENAME_CHAPTERS to be true as well
      - FORMAT=M4B
      - VERBOSE=true
      # - DRY_RUN=true 
```

**Additional context**
